name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and analyze on SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.Token git }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Put the name of your token here
        run: ./build-analyze.sh
        shell: bash
